language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libcurl-dev
      - libssl-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl; fi

script:
  - make
